### ISSUE TITLE
[CT-577] Fix: tables not being dropped after testing even though shows cascadle/drop happening in logs

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-redshift#110]
Past couple nights CI/CD have tagged https://github.com/dbt-labs/dbt-redshift/runs/6205412456?check_suite_focus=true 1040 failures for to many tables including temporary tables.

Looking in redshift test account showing that tables are stacking up and staying. even though test logs show drop call happening

### Expected behavior
tests should run/build tables/views and cleanup after run

### Screenshots and log output
cascade call:
[error log](https://github.com/dbt-labs/dbt-redshift/runs/6205412456?check_suite_focus=true#step:6:194)

integration test logs:
https://github.com/dbt-labs/dbt-redshift/runs/6205412456?check_suite_focus=true#step:6:1

**Comment by leahwicz** [comment]
@McKnight-42 let's prioritize looking into this and fixing it
