### ISSUE TITLE
[CT-837] Support IAM authentication for Redshift Serverless

### ISSUE THREAD

**Issue by mp24-git** [dbt-labs/dbt-redshift#138]
### Describe the feature
Redshift Serverless is generally available now. It supports connecting via IAM. dbt-redshift supports IAM for Redshift clusters, but not for serverless workgroups.

### Describe alternatives you've considered
At the moment, I can use database user and password to connect to Redshift Serverless

### Additional context
Redshift Serverless uses a different API than Redshift.

### Who will this benefit?
Anyone using Redshift Serverless and IAM.

### Are you interested in contributing this feature?
I have the PR ready.

**Comment by jtcohen6** [comment]
@mp24-git Thanks for opening the issue + corresponding PR!

**Comment by mp24-git** [comment]
For most cases, #251 should enable IAM authentication since the redshift_connector supports IAM with Redshift Serverless.
