### ISSUE TITLE
[CT-987] Relation does not exist when create new view

### ISSUE THREAD

**Issue by NessieLi** [dbt-labs/dbt-redshift#148]
### Describe the bug
Use drop cascade to drop my snapshot('notifications') and derived view('notifications_current') first. Then recreate the snapshot and related post view. The snapshot can be created successfully while the view can't.

### Steps To Reproduce
dbt run model to drop snapshot and cascaded view
dbt snapshot to recreate it
dbt run to create view

### Expected behavior
The view can be created

### Screenshots and log output
01:37:49  Completed with 1 error and 0 warnings:
01:37:49  
01:37:49  Database Error in model notifications_current (models/notifications_poc/notifications_current.sql)
01:37:49    relation "uat_conforming_notifications.notifications_current" does not exist

### System information
dbt core 1.1.0
```
<output goes here>
```

Redshift

python 3.9.13

**Comment by Fleid** [comment]
Hey @NessieLi, sorry for the delay!

Would you mind sharing a bit more about how you use `dbt run` to drop your snapshot?
I'm trying to reproduce the issue and I'm lost on that step :)

**Comment by Fleid** [comment]
I tried to reproduce by issuing a `drop table my_schema.my_snapshot table cascade` in Redshift. 

Then if I do a a `dbt run` it fails with the error message above.
But if I start with `dbt snapshot` before doing `dbt run`, then it doesn't reproduce your issue.

If you look in Redshift, is the missing table there? If you look at the output logs of the `dbt snapshot`, was the table properly created?

**Comment by Fleid** [comment]
Closing as stale, please re-open if need be.
