### ISSUE TITLE
[CT-1616] get_relation method returns None for Redshift external tables

### ISSUE THREAD

**Issue by tomekzbrozek** [dbt-labs/dbt-redshift#17]
### Describe the bug
`get_relation` method (https://docs.getdbt.com/docs/writing-code-in-dbt/jinja-context/adapter/#get_relation) returns `None` when provided with database, schema and table name of a Redshift external table (AWS Spectrum). 

### Steps To Reproduce
1. Create an external table with AWS Spectrum: https://docs.aws.amazon.com/redshift/latest/dg/c-spectrum-external-tables.html
2. Attempt to `get_relation` on that external table. 

### Expected behavior
Should return a regular relation as it does for native Redshift tables, e.g. an output like `analytics.spectrum_schema.mytable` instead of `None`

### Screenshots and log output
-

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: - - - )

**The output of `dbt --version`:**
```
0.16.0
```

**The operating system you're using:**
MacOS Mojave 

**The output of `python --version`:**
3.6.2

### Additional context
-

**Comment by jtcohen6** [comment]
Still a bug, still a good first issue for an interested community contributors!

**Comment by dbeatty10** [comment]
Resolved by https://github.com/dbt-labs/dbt-redshift/pull/428

**Comment by dbeatty10** [comment]
This [might not](https://github.com/dbt-labs/dbt-redshift/pull/428#issuecomment-1634232202) actually be resolved by #428 😅

Will either re-open this issue or keep closed depending on the outcome of that conversation.

If it is re-opened, the solution may look similar to https://github.com/dbt-labs/dbt-core/issues/7663, and it may make sense to solve them both at the same time.

**Comment by trymzet** [comment]
FWIW I've adapted [@dbeatty10's solution](https://github.com/dbt-labs/dbt-core/issues/7663#issuecomment-1584854886) for Spectrum and it worked for me (using `dbt-redshift==1.3.0` and `dbt-core==1.3.4`):

```diff
{% macro redshift__list_relations_without_caching(schema_relation) %}

  {% call statement('list_relations_without_caching', fetch_result=True) -%}
    select
        table_catalog as database,
        table_name as name,
        table_schema as schema,
        'table' as type
    from information_schema.tables
    where table_schema ilike '{{ schema_relation.schema }}'
    and table_type = 'BASE TABLE'
    union all
    select
      table_catalog as database,
      table_name as name,
      table_schema as schema,
      case
        when view_definition ilike '%create materialized view%'
          then 'materialized_view'
        else 'view'
      end as type
    from information_schema.views
    where table_schema ilike '{{ schema_relation.schema }}'
+    union all
+    select 
+        redshift_database_name as database,
+        tablename as name,
+        schemaname as schema,
+        'table' as type
+    from svv_external_tables
+    where schemaname ilike '{{ schema_relation.schema }}'
  {% endcall %}

  {{ return(load_result('list_relations_without_caching').table) }}

{% endmacro %}
```

**Comment by amychen1776** [comment]
Given the age of this issue and the lack of interactions, I'm going to close this out for now - to be reopened if folks express interest again. .
