### ISSUE TITLE
Redshift create table with backup option

### ISSUE THREAD

**Issue by krishbox** [dbt-labs/dbt-redshift#18]
### Describe the feature
The `CREATE TABLE` statement in Redshift has a configuration option that controls whether or not the table should be included in automated and manual cluster snapshots.  The default setting for this option is `YES`.  At present this is not configurable in DBT and the default is used for all table and incremental materialisations.

By allowing configuration of this parameter in DBT models we can save processing time when creating snapshots and restoring from snapshots and to reduce storage space on Amazon Simple Storage Service.

### Describe alternatives you've considered
There is no way to get around this except to turn off automated snapshots at a cluster level.

> To disable automated snapshots, set the retention period to zero. If you disable automated snapshots, Amazon Redshift stops taking snapshots and deletes any existing automated snapshots for the cluster.

### Additional context
This feature is Redshift specific.  The feature is similar but not exactly the same as Snowflakes `TRANSIENT` table.

### Who will this benefit?
This will benefit all DBT users who use Redshift and who want to control storage costs and to speed up snapshot creation and restores.

P.S. If you think this is worthwhile and in keeping with DBT's principles, then I would love to work on this issue with a PR.

**Comment by dlb8685** [comment]
@jtcohen6 I have some changes now in my local fork. Can you remind me which branch in dbt-redshift I should create a PR into? I'm assuming not `main`, but the other options look pretty random.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/6698709/142127408-2737537a-543a-45ea-b49d-526fbf0e0336.png">

**Comment by jtcohen6** [comment]
@dlb8685 `main` is right! We may not be able to get this in for v1, but that's where we'll want to merge it regardless, for inclusion in a future minor version.
