### ISSUE TITLE
[CT-1144] [CT-1093] [Bug] Incremental materialization alters model table to look like temporary table

### ISSUE THREAD

**Issue by kgregory-chariot** [dbt-labs/dbt-redshift#180]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We have created an incremental model. As part of the initial creation of this model, we have run a macro to add a primary key, which involves creating a temporary not-null column, populating it, and then replacing the original nullable column:

```
        alter table "{{table_relation.schema}}"."{{table_relation.identifier}}" add column TEMP_FOR_PK {{column_type}} not null default {{default_value}};
        update "{{table_relation.schema}}"."{{table_relation.identifier}}" set TEMP_FOR_PK = nvl( "{{column_name}}" :: {{column_type}}, {{default_value}});
        alter table "{{table_relation.schema}}"."{{table_relation.identifier}}" drop column "{{column_name}}";
        alter table "{{table_relation.schema}}"."{{table_relation.identifier}}" rename column TEMP_FOR_PK to "{{column_name}}";
```

However, DBT undoes this work as part of creating an incremental model:

```
13:42:15.480122 [debug] [Thread-1  ]: On model.redacted.example_model: /* {"app": "dbt", "dbt_version": "1.0.1", "profile_name": "default", "target_name": "default", "node_id": "model.redacted.example_model"} */

    alter table "keith"."warehouse"."example_model" add column "example_column__dbt_alter" character varying(259);
    update "keith"."warehouse"."example_model" set "example_column__dbt_alter" = "example_column";
    alter table "keith"."warehouse"."example_model" drop column "example_column" cascade;
    alter table "keith"."warehouse"."example_model" rename column "example_column__dbt_alter" to "example_column"
```

DBT then attempts to insert the new rows into the base table from the temporary table:

```
insert into "keith"."warehouse"."example_model" (REDACTED)
(
    select REDACTED
    from "example_model__dbt_tmp134213420791"
)
```

Which results in the following error from the database:

```
13:42:15.904777 [debug] [Thread-1  ]: Postgres adapter: Postgres error: cannot insert/update into table after dropping non-nullable column
```

### Expected Behavior

DBT would not change the base table. Instead, it would either (1) insert the rows from the temporary table as-is, or (2) it would alter the temporary table to match the base table.

### Steps To Reproduce

1. Create an incrementally materialized model with a post-hook that makes columns not-nullable and creates a primary key.
2. Perform a full refresh.
3. Perform an incremental refresh.

### Relevant log output

```shell
See log excerpts in Current Behavior section.
```

### Environment

```markdown
- OS: Ubuntu 20.0.4 (uname -a `Linux ip-10-150-179-62 5.15.0-1017-aws dbt-labs/dbt-core#21~20.04.1-Ubuntu SMP Fri Aug 5 11:44:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`)
- Python: 3.8.10
- dbt: 1.2.1
```

### Which database adapter are you using with dbt?

redshift

**Comment by bdgeise** [comment]
@dbeatty10 
`select version()` returns `PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.41533`

Our current workaround is to perform the same in the `on-run-end`

**Comment by kgregory-chariot** [comment]
While the underlying Redshift issue may be relevant, I think that the major problem is that DBT is trying to make the permanent (incrementally updated) table look like the temporary table, not the other way around.

Also, please note that `bdgeise` is the person directly affected by this: I was doing some consulting work for his team, but am not longer part of the project.

**Comment by Fleid** [comment]
Hi @bdgeise (and @kgregory-chariot),

The philosophy of dbt is to build model from their expression (the sql statement that defines them), not an existing object in the table. So it's expected that the incremental model looks like the temporary table (which looks like the model sql statement) and not the other way around.

Going back to the original issue, we are thinking about [supporting constraints as part of model contracts](https://github.com/dbt-labs/dbt-core/discussions/6726). Now would be a good time to chime in that conversation ;)

In the meantime, I'm wondering if the logic currently defined in the macro could not be ported in the model definition?

        alter table "{{table_relation.schema}}"."{{table_relation.identifier}}" add column TEMP_FOR_PK {{column_type}} not null default {{default_value}};
        update "{{table_relation.schema}}"."{{table_relation.identifier}}" set TEMP_FOR_PK = nvl( "{{column_name}}" :: {{column_type}}, {{default_value}});
        alter table "{{table_relation.schema}}"."{{table_relation.identifier}}" drop column "{{column_name}}";
        alter table "{{table_relation.schema}}"."{{table_relation.identifier}}" rename column TEMP_FOR_PK to "{{column_name}}";

```SQL

SELECT
    my_column as my_nullable_column,
    NVL(my_column,0) as my_column,
    ...
FROM ...
```

Or is it not practical in your case?

**Comment by Fleid** [comment]
I'm closing this for now, please comment below if you want me to re-open it.
Happy to chat more about this if need be.
