### ISSUE TITLE
Redshift distribution and sort key - default to auto or allow top level configuration

### ISSUE THREAD

**Issue by brangisom** [dbt-labs/dbt-redshift#20]
### Describe the feature
Redshift now has an `auto` option for table distribution and sort keys. Additionally, they have also released a feature, [Automatic Table Optimization](https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html), that allows Redshift to swap things out. This feature more or less automates the suggestions that show up in the `svv_alter_table_recommendations` system view, UI, etc. 

It would be super helpful to have that as the default, either by convention in DBT, or by configuration through allowing the dist ~~or sort~~ configuration values to be set in the `dbt_project.yml`. 

EDIT: Looks like sort keys can be set in `dbt_project.yml` already.

### Describe alternatives you've considered
A config() block in every model. 😢 

### Additional context
This is a Redshift database specific feature.

### Who will this benefit?
Anyone who uses Redshift, and would like to default to `auto` dist and/or sort keys to take advantage of the Automatic Table Optimization feature.

### Are you interested in contributing this feature?
Sure.

**Comment by misteliy** [comment]
this seems possible now https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_AS.html
