### ISSUE TITLE
[CT-1340] [Feature] Support Python models (dbt-py) on Redshift/AWS

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-redshift#204]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

## Background:

There's a [Spark redshift connector](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-redshift.html). This would allow user to run python transformation code on EMR cluster that load data from Redshift, and write transformed data back to Redshift. The whole process is very similar to using Dataproc to run python models on GCP/BigQuery.

## Items needed for implementation:
 
- If there's additional profile information needed for EMR cluster, we can add it as optional attributes at [Credentials](https://github.com/dbt-labs/dbt-redshift/blob/main/dbt/adapters/redshift/connections.py#L41)(existing example for [bigquery](https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/connections.py#L123)).
- We need one macro to generate the final code to run on EMR cluster, Previous example for dbt-bigquery [here](https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/include/bigquery/macros/materializations/table.sql#L51)
- Now that we have the profile info and the macro to generate final code, we need submission classes to submit python code to the cluster. [Existing submission code for dbt-bigquery](https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/python_submissions.py), Function to define in impl.py([link1](https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/impl.py#L851), [link2](https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/impl.py#L855)). And how those [classes are being used by dbt-core](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/base/impl.py#L1223)(This doesn't need to be changed.)

**Comment by colin-rogers-dbt** [comment]
I wonder if the right thing here to do is just pick on to implement with a long term of supporting both, can we leverage the existing spark/glue adapters?

**Comment by lostmygithubaccount** [comment]
new redshift integration with Apache Spark announced: https://aws.amazon.com/blogs/aws/new-amazon-redshift-integration-with-apache-spark/

**Comment by saraleon1** [comment]
+1 dbt Cloud Enterprise Customer - This team is using Redshift and are really interested in leveraging python models in their dbt project. Their AWS contact [passed this resource](https://docs.aws.amazon.com/redshift/latest/mgmt/python-driver-install.html) along as a possible way to run python + redshift.

**Comment by colin-rogers-dbt** [comment]
@lostmygithubaccount thanks for sharing, we should definitely look into leverage this! 

This is particularly interesting as it means we don't need to recreate the issues with the dbt-bigquery adapter where we shoehorned dataproc in. Going forward we should adhere to the rough principle that an adapter should only know how to leverage the capabilities of a single data transformation tool. If we want to support emr/glue we should focus on multi-adapter/project so folk can use the existing adapters for those tools.

**Comment by lostmygithubaccount** [comment]
@saraleon1 great to hear! on the Python connector there, we should use that in `dbt-redshift` in general for making the connection in the way we use the similar Snowflake connector. however, I don't think that'll get us Python models -- or at least not the ones we want. I see it can read into numpy or pandas locally, but we want to maintain the principle of executing Python code remotely (in the "warehouse")

@colin-rogers-dbt very much agreed! as fyi BigQuery was working on more native integration (forwarded you an email)

cc: @jtcohen6

**Comment by ryadav03** [comment]
Any ETA on this?

**Comment by zdravis** [comment]
Hi, is this feature going to be implemented? @colin-rogers-dbt

**Comment by viniciusnunest** [comment]
+1 Great ideia !

**Comment by dnascimento** [comment]
:+1  dbt-fal supports this but not with incremetal

**Comment by joshua-pgatour** [comment]
Would love this feature please.

**Comment by ipcleary** [comment]
+1

**Comment by cschouten** [comment]
+1

**Comment by rohaldb** [comment]
+1

**Comment by rohaldb** [comment]
I would really like to move my pipelines into DBT but don't want to lock myself into having to use SQL for transformations. So unfortuantely until this is done i'm going to have to stick to Glue :/

**Comment by erees-embarkvet** [comment]
+1

**Comment by marzaccaro** [comment]
Is this going to be implemented?

**Comment by spagnoloe-amenitiz** [comment]
+1, Redshift is one of the main DWHs in the market and this feature is a great tool for Data Science/Analytics. It is a pity not to have it there...
