### ISSUE TITLE
[CT-1389] [Feature] Redshift sort key AUTO should be supported

### ISSUE THREAD

**Issue by josephbrownskilljar** [dbt-labs/dbt-redshift#206]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Setting sort = AUTO results in the error:

` SORTKEY "auto" must be included in the select list`

### Describe alternatives you've considered

n/a

### Who will this benefit?

everyone who uses DBT with Redshift should benefit

### Anything else?

1. in dbt_project.yml, set:

models:
  +sort: auto
  +dist: auto

2. get the error `SORTKEY "auto" must be included in the select list`

This also fails when  added to the {{ config(...) }} block in model .sql files

- OS:any
- Python: 3.9.x
- dbt-core: 1.0.1
- dbt-redshift: 1.0.0

https://docs.getdbt.com/reference/resource-configs/redshift-configs

**Comment by jtcohen6** [comment]
This has come up before: https://github.com/dbt-labs/dbt-redshift/issues/20

The limitation in the past has been that `sortkey auto` is not supported with `create table as`. That appears to still be the case, judging by this documentation:
- https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_AS.html
- https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html
