### ISSUE TITLE
Redshift Serializable isolations and dbt transactions

### ISSUE THREAD

**Issue by nicku33** [dbt-labs/dbt-redshift#21]
### Describe the feature
We use dbt on top of Redshift at a decent scale. It's about 1600 models, many updated hourly and every quarter hour. We also have a large BI instance hooked up to the same database. As we approached 1000 BI users we started to have rampant serializable isolation violations in redshift. As you may know this is the only isolation available, but the granularity is at the table level. If the BI tool joins a source table for a dbt model and that model's output, it is very easy to get a non serializable sequence of events.

We have found that the inbuilt redshift materializations hold long transactions while doing the following:

Table:

1. CTAS into new table
2. ALTER cur -> old
3. ALTER new -> cur

Incremental:

1. CTAS into tmp table
2. delete from cur where id in tmp
3. insert into cur * from tmp

### Describe alternatives you've considered
We tried Redshift's new datashare feature to get, effectively, a kind of snapshot isolation but it's cumbersome.

### Who will this benefit?
Redshift users who encounter this issue. We're not sure how many there are out there. This could increase the commit queue delays since there are two commits but decrease the serialization issues. As well, in the table materialization, it could leave a stray _new table which is cleaned up in the next run, if you get a failure in the ALTER

### Are you interested in contributing this feature?
Our solution was to break the above into two separate transactions after each CTAS and have been running it for two weeks. It has reduced our serialization errors 100x. We can submit the code as a PR attached to this issue but wanted to see if this is something that would be accepted before we posted. They are done as:

```{% materialization incremental, adapter='redshift' -%}```

**Comment by ecsalomon** [comment]
We are running into this issue frequently as well. @nicku33 do you have a fork or change you could share with the workaround you implemented? Is it still working for you?

**Comment by Saurabhvartak** [comment]
Hey @nicku33 we are also getting the same error quite frequently (serializable isolation violation) can you share any workaround you implemented.

**Comment by b-moynihan** [comment]
Hey @nicku33 I'm also becoming increasingly effected by this error, if you could share any work around you have implemented it would be very much appreciated thank you 😁

**Comment by nicku33** [comment]
Hey sorry, I've been just buried lately.
Here is the materialization we wrote. 
We scan for locks all the time in redshift and migrate the lock-prone ones to this. It makes vacuum work really hard though. I think the hope is that since we are replacing all rows, you still get high scan rate since entire blocks will be marked deleted. Still it might be hard on the catalog.  I'm also trying to get someone from AWS/Redshift to chime in on this .

If `dbt` folk think this would make a good materialization for inclusion we'll make a PR. Maybe there's a better name than `soft_replace`

## soft_replace.sql
```
{% macro replace_all_rows(tmp_relation, target_relation) %}
    delete from {{ target_relation }} where true;
    insert into {{ target_relation }} ( select * from {{ tmp_relation }} );
{%- endmacro %}

{% materialization soft_replace, default -%}

  {% set target_relation = this.incorporate(type='table') %}
  {% set existing_relation = load_relation(this) %}
  {% set tmp_relation = make_temp_relation(this) %}

  {{ run_hooks(pre_hooks, inside_transaction=False) }}

  -- `BEGIN` happens here:
  {{ run_hooks(pre_hooks, inside_transaction=True) }}

  {% set to_drop = [] %}
  {% if existing_relation is none %}
      {% set build_sql = create_table_as(False, target_relation, sql) %}
  {% elif existing_relation.is_view or should_full_refresh() %}
      {#-- Make sure the backup doesn't exist so we don't encounter issues with the rename below #}
      {% set backup_identifier = existing_relation.identifier ~ "__dbt_backup" %}
      {% set backup_relation = existing_relation.incorporate(path={"identifier": backup_identifier}) %}
      {% do adapter.drop_relation(backup_relation) %}

      {% do adapter.rename_relation(target_relation, backup_relation) %}
      {% set build_sql = create_table_as(False, target_relation, sql) %}
      {% do to_drop.append(backup_relation) %}
  {% else %}
      {% set tmp_relation = make_temp_relation(target_relation) %}
      {% set create_sql = create_table_as(True, tmp_relation, sql) %}
      {% call statement("run_query_statement", fetch_result=false, auto_begin=true) %}
        {{ create_sql }}

      {% endcall %}
      -- COMMITTING so that our tmp table isn't holding up changes on what informed it
      {% do adapter.commit() %}

      {% do adapter.expand_target_column_types(
             from_relation=tmp_relation,
             to_relation=target_relation) %}
      {% set build_sql = replace_all_rows(tmp_relation, target_relation) %}
  {% endif %}

  {% call statement("main") %}
      {{ build_sql }}
  {% endcall %}

  {% do persist_docs(target_relation, model) %}

  {{ run_hooks(post_hooks, inside_transaction=True) }}

  -- `COMMIT` happens here
  {% do adapter.commit() %}

  {% for rel in to_drop %}
      {% do adapter.drop_relation(rel) %}
  {% endfor %}

  {{ run_hooks(post_hooks, inside_transaction=False) }}

  {{ return({'relations': [target_relation]}) }}

{%- endmaterialization %}
```

**Comment by kochalex** [comment]
@nicku33 thanks for your code.

What I did to make this less painful was add in a shell retry loop for any failed models - at least for us, this has really helped in **_practice_** - previously our runs failed most days and after adding we have succeeded on retry so far. However, I would imagine we are lot smaller in scale than many other folks, but in case anyone finds this useful too...

That said, we did have to move off of DBT cloud and run DBT ourselves in a scheduled container. DBT cloud jobs appear to only allow you to reference state for the last **passing** job - I wanted to add a 'follow up' retry job(s) in DBT cloud, but this type of retry selects errors from the previous run.

This runs `dbt run` via [poetry](https://python-poetry.org/) then loops through running it again, referencing state from the prior run to re-run any failed models until completion until the limit of 5 retries has been exhausted.

```bash
#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# function to handle retries, called later
function dbt_retry () {
  # retry any errors and downstream models
  if (poetry run dbt run --select result:error+ --defer --state previous_target)
  then
    echo "retry succeeded"
  else
    echo "retry failed: sleeping 1 minute"
    # copy target again to use success/failure state on the next retry
    sleep 60
    cp -r target previous_target && false
  fi
}

# remove ./target if it exists
rm -rf target
# do a full run normally
poetry run dbt run || true
cp -r target previous_target
# retry up to 5X for any fails
for i in 1 2 3 4 5; do dbt_retry && break; done

```

**Comment by nicku33** [comment]
We tried retries but eventually even that didn't work. This was a table which had, at any given time, 5-20 concurrent readers as it was read by BI. We needed low latency so no chance to materialize something uncontended.

**Comment by ecsalomon** [comment]
@nicku33 We incorporated the soft_replace materialization for our models that most frequently had serializable isolation violations and haven't experienced that issue in a week! Thank you for sharing!

**Comment by bendicethesecond** [comment]
Wonder if this can help: https://aws.amazon.com/about-aws/whats-new/2022/05/amazon-redshift-snapshot-isolation-level-support-concurrent-transactions/

**Comment by nicku33** [comment]
> Wonder if this can help: https://aws.amazon.com/about-aws/whats-new/2022/05/amazon-redshift-snapshot-isolation-level-support-concurrent-transactions/

It looks like snapshot support for DDL does not have rename table, which is the key to table swaps for 'table' materialization. https://docs.aws.amazon.com/redshift/latest/dg/c_serial_isolation.html
