### ISSUE TITLE
[CT-1504] [Feature] Replace `psycopg2` with `redshift_connector`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-redshift#219]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently, dbt-redshift inherits the DB API 2.0 Python connector from dbt-postgres (which [defaults to `psycopg2-binary`](https://github.com/dbt-labs/dbt-core/blob/66ac107409749ff1cf5dafeab371dd1baf916b9f/plugins/postgres/setup.py#L32-L40)).

[`redshift_connector`](https://pypi.org/project/redshift-connector/) is the Amazon Redshift connector for Python that implements [Python Database API Specification 2.0](https://www.python.org/dev/peps/pep-0249/) (PEP 249).

Implementing `redshift_connector` within dbt-redshift may unlock or ease other open issues like:
- https://github.com/dbt-labs/dbt-core/issues/6232
- https://github.com/dbt-labs/dbt-redshift/issues/204

### Describe alternatives you've considered

Leaving the [`psycopg2`](https://pypi.org/project/psycopg2/) is an option, but it might not support Redshift-specific functionality like mentioned above.

### Anything else?

This was discussed in a video call with @jtcohen6 and @Fleid earlier today, and it was affirmed that it might be time to take on this implementation.

**Comment by iklose** [comment]
This could also solve problems regarding Redshift Serverless connections with IAM authentication
