### ISSUE TITLE
[CT-1624] Remove dead code from tests/unit/utils.py

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-redshift#228]
We are consolidating the Parsed and Compiled node classes in dbt-core and renaming core/dbt/contracts/graph/parsed.py to core/dbt/contracts/graph/nodes.py.  The former file is referenced in tests/unit/utils.py, but none of those functions appear to be used.

Remove the unused functions from tests/unit/utils.py.

**Comment by VersusFacit** [comment]
These changes caused some errors in testing, so I'm addressing this ticket now to get us back on the rails.

Thanks Gerda for the explanation here!
