### ISSUE TITLE
[CT-1736] [Feature] Allow DISTSTYLE for dbt seed

### ISSUE THREAD

**Issue by WillAyd** [dbt-labs/dbt-redshift#255]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This feature would allow you to specify via the configuration what type of dist-style you would like for a seed-generated table

### Describe alternatives you've considered

The issue and workaround are described in this community forum post. While this works, it is less than ideal to have to create a second model:

https://discourse.getdbt.com/t/how-to-specify-distribution-sort-style-and-column-encoding-for-dbt-seeds-in-redshift/4858

### Who will this benefit?

Any user looking to control the DISTSTYLE of seed-generated Redshift tables. For small tables like those generated by a seed file, specifying DISTSTYLE ALL can having surprising performance benefits, as it prevents Redshift from broadcasting data across nodes when the table is joined to other tables

### Are you interested in contributing this feature?

Possibly

### Anything else?

I think this should borrow the `dist` keyword from the model config but make it available in the seed configuration. So something like:

```yml
version: 2

seeds:
  - name: utm_parameters
    config:
      schema: seed_data
      dist: all
```

Sort key could be handled similarly

**Comment by dbeatty10** [comment]
Hey @WillAyd ! Thanks for opening this and linking to the relevant discussion in the community forum.

One option would be to split this into two different PRs:
1. Just add `diststyle all` to the seed materialization for Redshift (without additional configuration ability)
1. Building on 1) above, add ability to configure DISTSTYLE, DISTKEY, and/or SORTKEY options for seeds

My primary reason for suggesting this split is that the implementation for the first effort might be quite simple, and provide good bang for the buck:
1. Make a copy of [`default__create_csv_table`](https://github.com/dbt-labs/dbt-core/blob/748a9328117d601560f056f3186e6a52572ff7a2/core/dbt/include/global_project/macros/materializations/seeds/helpers.sql#L6-L26) into a file in dbt-redshift named `dbt/include/redshift/macros/materializations/seeds/helpers.sql`
1. Rename the macro to `redshift__create_csv_table`
1. Add `diststyle all` in the appropriate location

The second part might not be too bad either, but would definitely be more involved in terms of testing, etc.

**Comment by niels** [comment]
Not stale.
