### ISSUE TITLE
[CT-1872] [CT-1870] [Feature] Delete+insert on redshift

### ISSUE THREAD

**Issue by herbertstos** [dbt-labs/dbt-redshift#274]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Hello, I'm trying use the incremental_strategy='delete+insert' on dbt  connected on redshift, but I can't do this working, looking for the dbt docs I see the dbt  incremental_strategy no has support to the redshift/postgres, it's right? I would like to put a column in a config and delete with base in this column and insert the values from staging table to fact table.

**Comment by dbeatty10** [comment]
Thanks for reaching out @herbertstos !

Could you give the following a try and see if it works for you in Redshift? It worked for me using `dbt-redshift==1.3.0`.

`models/incremental_delete_insert.sql`
```sql
{{
    config(
        materialized="incremental",
        incremental_strategy="delete+insert",
    )
}}


with data as (

    {% if not is_incremental() %}

        select 1 as id, cast('2020-01-01' as {{ dbt.type_timestamp() }}) as date_time union all
        select 2 as id, cast('2020-01-01' as {{ dbt.type_timestamp() }}) as date_time union all
        select 3 as id, cast('2020-01-01' as {{ dbt.type_timestamp() }}) as date_time

    {% else %}

        select 10 as id, cast('2020-01-01' as {{ dbt.type_timestamp() }}) as date_time union all
        select 20 as id, cast('2020-01-01' as {{ dbt.type_timestamp() }}) as date_time union all
        select 30 as id, cast('2020-01-02' as {{ dbt.type_timestamp() }}) as date_time union all
        select 40 as id, cast('2020-01-02' as {{ dbt.type_timestamp() }}) as date_time

    {% endif %}

)

select * from data
```

Run the following commands (which will use a different data set between the first command and the second):
```shell
dbt run -s incremental_delete_insert --full-refresh
dbt run -s incremental_delete_insert
```

**Comment by dbeatty10** [comment]
@herbertstos glad for the opportunity to look at this with you!

In general, my advice is to give **lots** of consideration before using a pre-hook or post-hook. Although they are necessary for some use cases, there is often a better alternative.

For your use case, did you try `incremental_strategy="delete+insert"` along with `unique_key="YOUR_COLUMN_NAME_HERE"`?

Here is an example that you can try both with and without `unique_key="id"`:
```sql
{{
    config(
        materialized="incremental",
        incremental_strategy="delete+insert",
        unique_key="id",
    )
}}


with data as (

    {% if not is_incremental() %}

        select 1 as id, cast('2020-01-01' as {{ dbt.type_timestamp() }}) as date_time union all
        select 2 as id, cast('2020-01-01' as {{ dbt.type_timestamp() }}) as date_time union all
        select 3 as id, cast('2020-01-01' as {{ dbt.type_timestamp() }}) as date_time

    {% else %}

        select 1 as id, cast('2020-01-01' as {{ dbt.type_timestamp() }}) as date_time union all
        select 2 as id, cast('2020-01-01' as {{ dbt.type_timestamp() }}) as date_time union all
        select 3 as id, cast('2020-01-02' as {{ dbt.type_timestamp() }}) as date_time union all
        select 4 as id, cast('2020-01-02' as {{ dbt.type_timestamp() }}) as date_time

    {% endif %}

)

select * from data
```

Just like before, run the following commands (which will use a different data set between the first command and the second):
```shell
dbt run -s incremental_delete_insert --full-refresh
dbt run -s incremental_delete_insert
```

**Comment by herbertstos** [comment]
@dbeatty10 yes, I tried yesterday all day, but I couldn't try to use both incremental_strategy="delete+insert" and unique_key="id", together and separately, but they didn't work for my case. whenever I try to do the second insert with the same data it tells me that it didn't insert any rows

**Comment by herbertstos** [comment]
@dbeatty10 yes, I tried yesterday all day, but I couldn't try to use both incremental_strategy="delete+insert" and unique_key="id", together and separately, but they didn't work for my case. whenever I try to do the second insert with the same data it tells me that it didn't insert any rows

**Comment by dbeatty10** [comment]
@herbertstos Did [this example](https://github.com/dbt-labs/dbt-redshift/issues/274#issuecomment-1398909718) work for you?

If you tried it, and it _didn't_ work, then please let me know.

If you tried it, and it _did_ work, then my recommendation is to _not_ use a pre-hook.

If you _did not_ try it, you should 😉 

Two tips for troubleshooting:
1. You can inspect the logs in `logs/dbt.log` to understand what's not working as you expected
1. [discourse.getdbt.com](https://discourse.getdbt.com/) is a great place for questions when you are stumped

**Comment by herbertstos** [comment]
hello @dbeatty10 
The example does not solve the problem.
delete insert behavior is not how I need it.

**Comment by herbertstos** [comment]
@dbeatty10 I schedule my dbt models on airflow with custom operators, I can't run with --full-refresh and without this always, I need the model delete records on redshift and insert the rows that are staging table.

**Comment by herbertstos** [comment]
@dbeatty10 thank you for feedback, now I was surfing in the dbt descourses, as you suggested it, and a found a topic, spiking about, what I need, https://discourse.getdbt.com/t/can-i-create-an-auto-incrementing-id-in-dbt/579
Well, In this moment I will need use the pre_hook, I'm sorry.

Thank you very much, for you time.

Have a good night.
