### ISSUE TITLE
[CT-1909] [CT-1903] Unable to generate docs from dbt core

### ISSUE THREAD

**Issue by jaswanth-gaddipati** [dbt-labs/dbt-redshift#281]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt docs generate 
throwing error
cross-db references allowed only in Redshift RA3.

but dbt compile is working properly

### Expected Behavior

dbt docs generate should generate docs

### Steps To Reproduce

define sources across dbs in redshift in dbt project
develop and execute models in a particular database
run dbt docs generate

### Environment

```markdown
- OS: windows
- Python:3.9
- dbt: 1.3.2
```

**Comment by dbeatty10** [comment]
Thanks for opening this issue @jaswanth-gaddipati !

Could you share more detail about the error it is throwing? i.e., could you share the relevant output and/or logs within `logs/dbt.log`?

**Comment by dbeatty10** [comment]
I did some more research @jaswanth-gaddipati. I see now that you mentioned precise error was something like:
```
Cross-db references allowed only in Redshift RA3.* node. Got X
```

Could you try adding `ra3_node` to your `profiles.yml` configuration like below (and demonstrated [here](https://docs.getdbt.com/reference/warehouse-setups/redshift-setup#password-based-authentication) and [here](https://github.com/dbt-labs/dbt-core/pull/3408#issuecomment-855823005))?
```yaml
  target: dev
  outputs:
    dev:
      type: redshift
      ...
      ra3_node: true # enables cross-database sources
```

[Apparently](https://github.com/dbt-labs/dbt-core/issues/5297), this configuration should enable cross-database sources if you are not actually using RA3 nodes.

One [known problem](https://github.com/dbt-labs/dbt-redshift/issues/94) is that dbt Cloud users do not have access to custom `profiles.yml` fields today, so this option won't be a possibility if you are a dbt Cloud user.

**Comment by jaswanth-gaddipati** [comment]
Hi @dbeatty10 

Thank you. I am able to generate docs.

**Comment by dbeatty10** [comment]
> Thank you. I am able to generate docs.

🙌 Awesome @jaswanth-gaddipati !

> can we create models in redshift across DBs

I don't think so due to the [known limitations](https://docs.aws.amazon.com/redshift/latest/dg/cross-database_limitation.html). I'm _guessing_ you would need separate dbt projects per database. But if you discover that it does work somehow, please let us know!

Since generating the docs is working for you now, I'm going to close this issue. You can open a new one if you run into any bugs or have any feature requests.
