### ISSUE TITLE
[CT-2071] [Bug] adapter.get_columns_in_relation returning columns that no longer exist in pg_table_def

### ISSUE THREAD

**Issue by khgould** [dbt-labs/dbt-redshift#315]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Columns that do not exist in the table are being returned by the adapter.get_columns_in_relation function. I believe the pg table should be considered the source of truth. I'm unable to find the source code for the adapter.get_columns_in_relation to compare what table its retrieving from. 

Relevant macros/pkgs include salesforce_formula_utils/macros/sfdc_star_exact.sql - which currently returns columns that no longer exist

### Expected Behavior

Only columns currently returned from pg_table_def are included in the result from the adapter

### Steps To Reproduce

1. dbt-redshift
2. remove a column from some table (perhaps salesforce source table e.g account)
3. execute select "column" from pg_table_def where tablename = <tablename> and schemaname = <schema>
4. create a model like so: (from dbt docs)
```{%- set columns = adapter.get_columns_in_relation(source('schema', 'table')) -%}

{% for column in columns %}
  {{ log("Column: " ~ column, info=true) }}
{% endfor %} 
```

5. Compare columns from 4 and 5. 5 is showing columns that no longer exist in 4

### Environment

```markdown
- OS: macOS-13.1-x86_64-i386-64bit
- Python: 3.10.9
- dbt-core: 1.4.1
- dbt-redshift: 1.4.0
```

**Comment by dbeatty10** [comment]
Hey @khgould thanks for reaching out!

### Source code
[Here](https://github.com/dbt-labs/dbt-redshift/blob/34f9212249aeeeff980b53c3b5026b6fd37c83b3/dbt/include/redshift/macros/adapters.sql#L81) is where you can see the logic of `adapter.get_columns_in_relation` for dbt-redshift. It looks like it is combining data from the following:
- `information_schema."columns"`
- [`pg_get_late_binding_view_cols()`](https://docs.aws.amazon.com/redshift/latest/dg/PG_GET_LATE_BINDING_VIEW_COLS.html)
- [`pg_catalog.svv_external_columns`](https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_COLUMNS.html)

### Unable to reproduce so far
I tried to reproduce what you described, but fell short. Here is what I tried:

`dbt_project.yml`
```yaml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "my_profile"
```

`models/simple_table.sql`
```sql
{{
  config(
    materialized='table',
  )
}}

select 1 as id, 2 as my_number
```

`analyses/test.sql`
```sql
{%- set relation = ref("simple_table") -%}

{{ relation }}

-- Columns from `adapter.get_columns_in_relation` before:
{{ adapter.get_columns_in_relation(relation) }}

-- Delete the column "my_number" from the model
{%- set query = "alter table " ~ relation ~ " drop column my_number;" %}
{{ query }}
{%- set results = run_query(query) %}

-- Columns from `adapter.get_columns_in_relation` after:
{{ adapter.get_columns_in_relation(relation) }}
```

```shell
dbt run -s simple_table
dbt compile -s analyses/test.sql
```

Output:

`target/compiled/my_dbt_project/analyses/test.sql`
```
"my_database"."my_schema"."simple_table"

-- Columns from `adapter.get_columns_in_relation` before:
[<Column id (integer)>, <Column my_number (integer)>]

-- Delete the column "my_number" from the model
alter table "my_database"."my_schema"."simple_table" drop column my_number;

-- Columns from `adapter.get_columns_in_relation` after:
[<Column id (integer)>]
```

Are you able to tweak this example in any way to get it to return more columns than you expect? Or can you share more details of how to set up a project to trigger the difference that you are seeing?

Something to note: I don't actually have permission to query from `pg_table_def` with the credentials I am using for my dbt user.

**Comment by khgould** [comment]
Doug - thank you for looking into this.
I believe I was mistaken. It's not that the adapter is pulling in columns
that no longer exist ... it's that my dev and prod target databases have
different columns. I was compiling in one, and trying to execute in
another. Shame on me!

Consider this closed.

--
KG

**Comment by dbeatty10** [comment]
No worries @khgould -- glad that there's an explanation for the observed behavior!
