### ISSUE TITLE
[CT-2156] [Feature] Add dbt-redshift connection methods - Auth Profile and IdP Credentials(Azure and Okta Identity Providers)

### ISSUE THREAD

**Issue by jiezhen-chen** [dbt-labs/dbt-redshift#332]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Provide additional authentication methods to connect to dbt-redshift. The new code changes will allow users to connect to dbt-redshift using authentication profiles and Identity Provider (IdP) Plugins for Azure and Okta. Users will need to provide required parameters specified in [this Redshift documentation](https://docs.aws.amazon.com/redshift/latest/mgmt/odbc20-authentication-ssl.html) when configuring profiles.yml in order to authenticate using these new methods.

**Comment by dbeatty10** [comment]
Thanks for opening @jiezhen-chen !

I'm assuming you created this issue to link to https://github.com/dbt-labs/dbt-redshift/pull/323 ([per request](https://github.com/dbt-labs/dbt-redshift/pull/323#issuecomment-1438831963) of @Fleid) ?

**Comment by jiezhen-chen** [comment]
> Thanks for opening @jiezhen-chen !
> 
> I'm assuming you created this issue to link to #323 ([per request](https://github.com/dbt-labs/dbt-redshift/pull/323#issuecomment-1438831963) of @Fleid) ?

yes!

**Comment by dbeatty10** [comment]
Awesome!

I added the issue number here to link it with the pull request:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/44704949/220478816-1c573744-fc11-4185-81f5-b72266ec9d16.png">

**Comment by jaklan** [comment]
@dbeatty10 @jiezhen-chen I don't see it covered in the feature request, but it would be really crucial to also support the generic plugin:
<img width="1000" alt="image" src="https://github.com/dbt-labs/dbt-redshift/assets/24907857/ec1b4866-2821-4640-adff-b52f870fb9e5">

**Comment by misteliy** [comment]
Any update on this?

**Comment by jaklan** [comment]
bump

**Comment by jaklan** [comment]
bump
