### ISSUE TITLE
[ADAP-424] [Bug] Snapshot functionality does not handle a column change from varchar to SUPER

### ISSUE THREAD

**Issue by darekdade** [dbt-labs/dbt-redshift#388]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

A column in a source table changed from varchar to SUPER. We expected the snapshot command to handle that schema change gracefully but instead it errored out with 
```
Database Error in snapshot my_snapshot (snapshots/fit/my_snapshot.sql)
column "json_column" is of type character varying but expression is of type super
HINT:  You will need to rewrite or cast the expression.
```

### Expected Behavior

I expected the snapshot table to be recreated with an updated SUPER column. 

### Steps To Reproduce

1. Create a snapshot of a source table with a varchar column
2. Change the varchar column type to SUPER
3. Run a snapshot on that same source table

### Relevant log output

```shell
Database Error in snapshot my_snapshot (snapshots/fit/my_snapshot.sql)
column "json_column" is of type character varying but expression is of type super
HINT:  You will need to rewrite or cast the expression.
```

### Environment

```markdown
- OS: CentOS Linux release 7.8.2003
- Python: 3.7.3
- dbt-core: 1.1.0
- dbt-redshift: 1.1.0
```

**Comment by Fleid** [comment]
Data type changes are not supported in snapshots. Only value mutations are handled.
If the database handles implicit conversion, I think they may go through, but that's a nice side effect, not a capability.

I will close this bug, but please let me know if you think this should be an improvement made to snapshots, and I'll re-open as enhancement.
