### ISSUE TITLE
[ADAP-437] [Feature] Enable "merge" incremental strategy for Redshift

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-redshift#402]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Per @kbrock91, we would like to enable Redshift users to use the `merge` strategy for incremental materializations. This is the same thing as https://github.com/dbt-labs/dbt-core/issues/6696 but for Redshift also.

Implementation may be as simple as adding the following to `dbt/adapters/redshift/impl.py`:

```python
    def valid_incremental_strategies(self):
        """The set of standard builtin strategies which this adapter supports out-of-the-box.
        Not used to validate custom strategies defined by end users.
        """
        return ["append", "delete+insert", "merge"]
```

https://github.com/dbt-labs/dbt-redshift/pull/318 is an open PR that is related.

### Describe alternatives you've considered

N/A

### Who will this benefit?

Redshift users seeking to use the `merge` strategy for incremental materializations.

### Are you interested in contributing this feature?

N/A

### Anything else?

https://docs.aws.amazon.com/redshift/latest/dg/r_MERGE.html

> This is prerelease documentation for the MERGE command, which is in preview release. The documentation and the feature are both subject to change. We recommend that you use this feature only with test clusters, and not in production environments. Public preview will end on April 5, 2023. Preview clusters and preview serverless workgroups and namespaces will be removed automatically two weeks after the end of the preview. For preview terms and conditions, see Betas and Previews in [AWS Service Terms](https://aws.amazon.com/service-terms/).

**Comment by mrcool4** [comment]
We are also interested in this feature. Any ETA would be appreciated. Thanjs

**Comment by Kamalakar4Pelago** [comment]
+1,  any ETA please

**Comment by sarojts** [comment]
+1

**Comment by dbeatty10** [comment]
@jiezhen-chen I was just talking with @dataders, and he mentioned that you might be interested in opening a PR for this one?

**Comment by jiezhen-chen** [comment]
@dbeatty10 Sorry didn't get back to you sooner. I've opened a PR for this: https://github.com/dbt-labs/dbt-redshift/pull/490
