### ISSUE TITLE
[ADAP-458] [Bug] Late binding views strange ddl

### ISSUE THREAD

**Issue by janposlusny** [dbt-labs/dbt-redshift#409]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When trying to create a late-binding view, I will end up with this ddl in database:
```sql
CREATE OR REPLACE VIEW schema.view_name
AS /* {"app": "dbt", "dbt_version": "1.4.5", "profile_name": "profile", "target_name": "prod", "node_id": "model.profile.view_name"} */


  create view "view_name" as (
  select ... 
  ) with no schema binding;
```

### Expected Behavior

I would expect to obtain
```sql
create or replace view schema.view_name as (
  select ... 
) with no schema binding;
```

### Steps To Reproduce

- add late binding in `dbt_project.yml` file (as described [here](https://docs.getdbt.com/reference/resource-configs/redshift-configs#late-binding-views))
- run your view with `dbt run --select view`
- check in redshift the ddl for created view

### Environment

```markdown
- OS: macOS Ventura 13.3.1
- Python: 3.11.2
- dbt-core: 1.4.5
- dbt-redshift: 1.4.0
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @janposlusny !

Could you try my setup below and see if it works for you or not? It worked for me without issue (that I could see).

If it doesn't work, could you share the following?
- Where are you seeing that DDL with the uppercase `CREATE OR REPLACE VIEW ...` part?
- What is the content of your `models/view_name.sql` file?

### What worked for me
`dbt_project.yml`
```yaml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "sandcastle-redshift"

models:
  +bind: false # Materialize all views as late-binding
  my_dbt_project:
    enabled: true
```

`models/my_view.sql`
```
{{ config(materialized='view', bind=False) }}

select 1 as id
```

Then I ran this:
```shell
dbt run --select my_view
```

This looked good:

`target/run/my_dbt_project/models/my_view.sql`
```sql


  create view "my_database"."dbt_dbeatty"."my_view__dbt_tmp" as (
    

select 1 as id
  ) with no schema binding;

```

When I queried [stl_ddltext](https://docs.aws.amazon.com/redshift/latest/dg/r_STL_DDLTEXT.html), I got something like the following:
```sql
create view "my_database"."dbt_dbeatty"."my_view__dbt_tmp" as (
    

select 1 as id
  ) with no schema binding;

alter table "my_database"."dbt_dbeatty"."my_view" rename to "my_view__dbt_backup"                                                                                                                                                                             

alter table "my_database"."dbt_dbeatty"."my_view__dbt_tmp" rename to "my_view"                                                                                                                                                                                

drop view if exists "my_database"."dbt_dbeatty"."my_view__dbt_backup" cascade                                                                                                                                                                                 
```

**Comment by janposlusny** [comment]
<img src="https://media.tenor.com/Oaq1HNMNDVsAAAAC/facepalm-crowd.gif" height="100" />

Sorry my bad. I checked `stl_ddltext` and everything is ok. It seems it might be an issue of `dbeaver` how it generates ddl (it had [similar](https://github.com/dbeaver/dbeaver/issues/8701) in the past).

My apologies and thank you very much for your detailed reply! 🙏 👋
Closing the issue as it is not an issue of `dbt`.
