### ISSUE TITLE
[ADAP-557] [Regression] run-operation with run_query macro does not commit changes

### ISSUE THREAD

**Issue by IDoneShaveIt** [dbt-labs/dbt-redshift#451]
### Is this a regression in a recent version of dbt-redshift?

- [X] I believe this is a regression in dbt-redshift functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

When running `run-operation` command with the macro `run_query` that updates rows in the DWH, the changes are not being committed and the data is not getting updated although the `run-operation` ran successfully.
(This is happening with insert queries as well).

The macro I am running using run-operation is:
```sql
{% macro update_sent_alerts(alert_ids, sent_at, table_name) %}
    {% if alert_ids %}
        {% set update_sent_alerts_query %}
            UPDATE {{ ref(table_name) }} set suppression_status = 'sent', sent_at = {{ "'{}'".format(sent_at) }}, alert_sent = TRUE
            WHERE alert_id IN {{ elementary.strings_list_to_tuple(alert_ids) }} and suppression_status = 'pending' and
                {{ elementary.edr_cast_as_timestamp('detected_at') }} >= {{ get_alerts_time_limit() }}
        {% endset %}
        {% do run_query(update_sent_alerts_query) %}
    {% endif %}
{% endmacro %}
```

I tested it with other macros that uses `run_query` with a simple update / insert query, and the result is the same.

### Expected/Previous Behavior

Before using `dbt-redshift 1.5.0`, the `run-operation` command was updating the data successfully at the DWH.

### Steps To Reproduce

1. Create a macro that uses `run_query` with a query that inserts / updates data.
2. Run `dbt run-operation` with the macro using `dbt redshift 1.5.0` and above.
3. Check the data at the DWH and see that it was not updated.

### Environment

```markdown
- OS: macOS Monterey 12.4
- Python: 3.9.13
- dbt-core (working version): 1.5.0
- dbt-redshift (working version): 1.5.1
- dbt-core (regression version): 1.4.6
- dbt-redshift (regression version): 1.4.0
```

**Comment by dbeatty10** [comment]
Thanks for finding and reporting another regression @IDoneShaveIt 🙏

I was able to reproduce the error you are reporting with the simple example below:

### Reprex

`models/my_model.sql`
```sql
{{ config(materialized="table") }}

select 1 as id, 'pending' as status
```

`macros/test_update.sql`
```sql
{% macro update_some_model(alert_ids, sent_at, table_name) %}
      {% set update_query %}
          UPDATE {{ ref(my_model) }} set status = 'sent'
      {% endset %}
      {% do run_query(update_query) %}
{% endmacro %}
```

```shell
dbt run
```

You can examine it like this with dbt-core >= 1.5:
```shell
dbt show --inline "select * from {{ ref('my_model') }}"
```

Then run the macro:
```shell
dbt run-operation update_some_model --args '{}'
```

See that it didn't update:
```shell
dbt show --inline "select * from {{ ref('my_model') }}"
```

### Log output

Here's my log output from `logs/dbt.log` with the timestamps, etc stripped out:
```
Acquiring new redshift connection 'macro_update_some_model'
Using redshift connection "macro_update_some_model"
On macro_update_some_model: BEGIN
Opening a new connection, currently in state init
Redshift adapter: Connecting to redshift with username/password based auth...
SQL status: SUCCESS in 1.0 seconds
On macro_update_some_model: COMMIT
Using redshift connection "macro_update_some_model"
On macro_update_some_model: COMMIT
SQL status: SUCCESS in 0.0 seconds
Using redshift connection "macro_update_some_model"
On macro_update_some_model: UPDATE "test_database"."dbt_dbeatty"."my_model" set status = 'sent'
SQL status: SUCCESS in 5.0 seconds
On macro_update_some_model: Close
Command `dbt run-operation` succeeded at 07:20:25.234958 after 5.93 seconds
Connection 'macro_update_some_model' was properly closed.
Flushing usage events
```

**Comment by dbeatty10** [comment]
> If I replace `get_custom_schema_names` with a hard-coded list of schemas, then the operation runs as expected.

This is surprising that dbt-redshift 1.7.7 is behaving differently depending if `get_custom_schema_names()` is a hard-coded list or not.

How is it behaving when it is hard-coded? And how it is behaving when it is not hard-coded?

Is there a version of dbt-redshift that is working how you expect?

Bonus: could you provide a simplified version of your `get_custom_schema_names()` macro?
