### ISSUE TITLE
[ADAP-563] [Regression] Seeds larger than ~200KB are not loaded in 1.5

### ISSUE THREAD

**Issue by kostek-pl** [dbt-labs/dbt-redshift#455]
### Is this a regression in a recent version of dbt-redshift?

- [X] I believe this is a regression in dbt-redshift functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

After upgrade to dbt 1.5 some of our seed(we noticed that for larger than about 200KB) are not loaded anymore

We get an error:

'h' format requires -32768 <= number <= 32767

### Expected/Previous Behavior

seeds should be loaded

### Steps To Reproduce

create simple test project with dbt init
try to load sample csv file like https://www.stats.govt.nz/assets/Uploads/Business-financial-data/Business-financial-data-September-2022-quarter/Download-data/business-financial-data-september-2022-quarter-csv.zip
 

### Relevant log output

```shell
DBT 1.5

16:04:29  Running with dbt=1.5.0
16:04:31  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 345 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics, 0 groups
16:04:31  
16:04:37  Concurrency: 1 threads (target='dev')
16:04:37  
16:04:37  1 of 1 START seed file test.sample_business_financial_data ................. [RUN]
16:05:01  1 of 1 ERROR loading seed file test.sample_business_financial_data ......... [ERROR in 23.27s]
16:05:02  
16:05:02  Finished running 1 seed in 0 hours 0 minutes and 31.18 seconds (31.18s).
16:05:02  
16:05:02  Completed with 1 error and 0 warnings:
16:05:02
16:05:02  Runtime Error in seed sample_business_financial_data (seeds\sample_business_financial_data.csv)
16:05:02    'h' format requires -32768 <= number <= 32767
16:05:02
16:05:02  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1

DBT 1.3

15:59:55  Running with dbt=1.3.4
15:59:55  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 327 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics
15:59:55
16:00:07  Concurrency: 1 threads (target='dev')
16:00:07
16:00:07  1 of 1 START seed file test.sample_business_financial_data ................. [RUN]
16:00:43  1 of 1 OK loaded seed file test.sample_business_financial_data ............. [INSERT 6195 in 35.66s]
16:00:44
16:00:44  Finished running 1 seed in 0 hours 0 minutes and 48.55 seconds (48.55s).
16:00:44
16:00:44  Completed successfully
16:00:44
16:00:44  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: windows/linux
- Python: 3.9.16, 3.10.10
- dbt-core (working version): 1.3.4
- dbt-redshift (working version): 1.3.0
- dbt-core (regression version): 1.5.0
- dbt-redshift (regression version): 1.5.1
```

**Comment by kostek-pl** [comment]
It also works on 1.4

05:31:21  Running with dbt=1.4.6
05:31:21  Unable to do partial parsing because of a version mismatch
05:31:22  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 329 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics
05:31:22  
05:31:26  Concurrency: 1 threads (target='dev')
05:31:26  
05:31:26  1 of 1 START seed file test.sample_business_financial_data ................. [RUN]
05:31:53  1 of 1 OK loaded seed file test.sample_business_financial_data ............. [INSERT 6195 in 27.18s]
05:31:53  
05:31:53  Finished running 1 seed in 0 hours 0 minutes and 31.46 seconds (31.46s).
05:31:53  
05:31:53  Completed successfully
05:31:53  
05:31:54  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1

**Comment by kylezeeuwen** [comment]
> Thank you for reporting this @kostek-pl !
> 
> This appears the same as #347, so I'm going to close this as a duplicate.
> 
> In the meantime, could you try the following workaround?
> 
> * set the max batch size for seeds within your project
> 
> `macros/get_batch_size.sql`
> 
> ```sql
> {% macro get_batch_size() %}
>   {{ return(1000) }}
> {% endmacro %}
> ```
> 
> Basically, you'd changing `1000` to a small enough number that your error goes away.

This workaround worked for me on a 800K seed file - noting that I would rather not have it as a seed and it was just an experiment :)

dbt-redshift==1.5.1
dbt=1.5.0
