### ISSUE TITLE
[ADAP-611] [Bug] When any of the unique keys is null incremental model duplicates data

### ISSUE THREAD

**Issue by alejandrofm** [dbt-labs/dbt-redshift#486]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When one or more unique keys have NULL values on the table, the incremental model appends a row instead of replacing the existing one.
So:
1, NULL, 1 duplicates the record
1, 2, 1 works ok

### Expected Behavior

take null into account on unique keys of incremental models

### Steps To Reproduce

set a unique key that could have NULL values.
run the incremental model twice 

### Environment

```markdown
- OS: Ubuntu
- Python: 3.8
- dbt-core: 1.4
- dbt-redshift: 1.4
```

**Comment by Fleid** [comment]
Hi @alejandrofm, it looks like you stumbled on that edge case, documented [here](https://docs.getdbt.com/docs/build/incremental-models#defining-a-unique-key-optional):

> Columns used in this way should not contain any nulls, or the incremental model run may fail. Either ensure that each column has no nulls (for example with coalesce(COLUMN_NAME, 'VALUE_IF_NULL')), or define a single-column [surrogate key](https://docs.getdbt.com/terms/surrogate-key) (for example with [dbt_utils.generate_surrogate_key](https://github.com/dbt-labs/dbt-utils#generate_surrogate_key-source)).

I am closing this issue for now, but please do re-open if you think your issue is something else.
In any case, thanks a lot for submitting this issue :)
