### ISSUE TITLE
[ADAP-721] [Bug] [Regression] Canceled or failed run creates a Database Error

### ISSUE THREAD

**Issue by hacherix** [dbt-labs/dbt-redshift#553]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When dbt tries to cancel a query it raises a Database Error with the pid as output:
```
Encountered an error:
Database Error
  syntax error at or near "123456789"
```
The cases I noticed that are triggering this bug but they may not be exhaustive:
* Cancel a dbt execution while models or tests are running
* A model is failing because of an error while running `--fail-fast` and other running models are cancelled

This is happening only since version 1.5, I don't see the issue on previous versions.

Debugging guess, not tested:
* As per [redshift-connector documentation](https://github.com/aws/amazon-redshift-python-driver#query-using-functions) `fetchone()` seems to return an array instead of a tuple like in psycopg. 
* When a query is cancelled the array is provided instead of the pid, which results in the error. Example: `select pg_terminate_backend([123456789]);`.
https://github.com/dbt-labs/dbt-redshift/blob/cbb45ca585a61b1bb250b48aac69c410f8ef4efb/dbt/adapters/redshift/connections.py#L253

Thanks a lot for your help! I am available if you need more information :)

### Expected Behavior

The query should be cancelled without any error and print usual logs.

### Steps To Reproduce

**Easy steps to reproduce**
1. Use Jaffle Shop project
2. Run the DAG
3. Cancel it while queries are still in `RUN` status (with ctrl+C)
4. Look at the error log

**Harder steps to reproduce**
1. Use a big project which have big models running in parallel (Jaffle Shop project is too simple)
2. Update a model usually running in parallel to make it fail
3. Run the DAG with `--fail-fast`
6. Look at the error log

### Relevant log output

```shell
❯ dbt run 

08:31:16  Running with dbt=1.5.3
08:31:16  Registered adapter: redshift=1.5.8
08:31:17  Found 5 models, 20 tests, 0 snapshots, 0 analyses, 346 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
08:31:17  
08:31:23  Concurrency: 4 threads (target='dev')
08:31:23  
08:31:23  1 of 5 START sql view model dev.stg_customers .......................... [RUN]
08:31:23  2 of 5 START sql view model dev.stg_orders ............................. [RUN]
08:31:23  3 of 5 START sql view model dev.stg_payments ........................... [RUN]
^C08:31:28  
08:31:28  Finished running  in 0 hours 0 minutes and 10.50 seconds (10.50s).
08:31:28  Encountered an error:
Database Error
  syntax error at or near "1073857832"
08:31:28  3 of 5 ERROR creating sql view model dev.stg_payments .................. [ERROR in 4.89s]
08:31:28  2 of 5 ERROR creating sql view model dev.stg_orders .................... [ERROR in 4.90s]
08:31:28  1 of 5 ERROR creating sql view model dev.stg_customers ................. [ERROR in 4.90s]
```

### Environment

```markdown
- OS: MacOS 13.4.1 Intel
- Python: 3.9.16
- dbt-core: 1.5.3
- dbt-redshift: 1.5.8
```

**Comment by olly-writes-code** [comment]
We're also noticing this. cc @stlee-aurora

**Comment by dbeatty10** [comment]
Thanks for reporting this @hacherix and @olly-writes-code !

I've raised a PR to fix this: https://github.com/dbt-labs/dbt-redshift/pull/568

**Comment by max-santiago** [comment]
Hi! is there anything blocking this PR?

**Comment by hacherix** [comment]
Thanks for the MR @dbeatty10! Any reason why it is not merged? Is there anything we can do to help?

**Comment by patkearns10** [comment]
@mikealfare / @dbeatty10  -- should we backport this to 1.6?
