### ISSUE TITLE
[ADAP-759] [CT-2925] can't turn back to 1.5 from 1.6 without issues

### ISSUE THREAD

**Issue by heshamh96** [dbt-labs/dbt-redshift#566]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

i was trying to use the materialized views in 1.6 but it didn't work as expected on red shift so i downgraded to 1.5 ...but it tells me there is an os error regarding the connections when i try to dbt debug although the profiles.yml file was already working before .... 

note .... i tried to install 1.5 ion a clean python environemtn but the issue still prisists .... so apparently somthing in my project changed when i used dbt 1.6 ... so i'm not sure what that is .... but i need some support

### Expected Behavior

when i downgrade to dbt 1.5  my project should be working as it was before i guess

### Steps To Reproduce

i upgraded to 1.6 ... 
i then tried to pip install -U dbt-redshift==1.5
and then i tried:   dbt parse 
then i issued  : dbt debug
and then i got the following error

' 18:14:56    cluster_id: None
18:14:56    iam_profile: None
18:14:56    sslmode: None
18:14:56  Registered adapter: redshift=1.5.0
18:14:56    Connection test: [ERROR]

18:14:56  1 check failed:
18:14:56  dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  ('communication error', OSError('Int or String expected'))
'

### Relevant log output

```shell
18:14:56    cluster_id: None
18:14:56    iam_profile: None
18:14:56    sslmode: None
18:14:56  Registered adapter: redshift=1.5.0
18:14:56    Connection test: [ERROR]

18:14:56  1 check failed:
18:14:56  dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  ('communication error', OSError('Int or String expected'))
```

### Environment

```markdown
- OS:pop-OS
- Python:3.10
- dbt:1.6
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

![image](https://github.com/dbt-labs/dbt-core/assets/24191100/380d944f-c9d6-40ab-b5cc-2e804908239b)

**Comment by PeterGroesbeck** [comment]
@dbeatty10 I'm also having this issue. I've tried installing 1.5.1/3/5/8 and am now on 1.6.0 but I can't seem to resolve the issue:

```
$ dbt compile
22:53:41  Running with dbt=1.6.0
22:53:42  Registered adapter: redshift=1.6.0
22:53:42  Unable to do partial parsing because of a version mismatch
22:53:42  Found 97 models, 1 operation, 2 tests, 11 sources, 0 exposures, 0 metrics, 400 macros, 0 groups, 0 semantic models
22:53:42  
22:53:42  Encountered an error:
Database Error
  ('communication error', gaierror(8, 'nodename nor servname provided, or not known'))
```
