### ISSUE TITLE
[ADAP-911] Support Metadata Freshness

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-redshift#615]
### Describe the feature

Support metadata-based freshness by implementing the new macro and feature flag described in [#7012](https://github.com/dbt-labs/dbt-core/issues/7012).

### Who will this benefit?

Everyone who wants faster freshness results from Redshift!

**Comment by misteliy** [comment]
Any updates on this issue given dbt 1.7 is coming up?

**Comment by misteliy** [comment]
Hi, currently we have over 15k sources and having the freshness through metadata instead of querying redshift and putting more pressure on the cluster would be extremely useful.

**Comment by mikealfare** [comment]
I set this up, but after doing some research it seems that Redshift may not support this. I have a request out to our partner team at Redshift; hopefully I'm missing something. Either way, I'm putting this on hold until then.

**Comment by mikealfare** [comment]
Re-opening for the backport.
