### ISSUE TITLE
[ADAP-927] [Feature] Update boto3 to 1.29.* version

### ISSUE THREAD

**Issue by samjeckert** [dbt-labs/dbt-redshift#624]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Boto3 is pinned to the 1.26.* series, which is three major versions behind. This prevents use of updated awscli, boto3, botocore in conjunction with dbt-redshift

**Comment by dataders** [comment]
No objection to this! Would you like to open the PR? Certainly a low-hanging effort. If you're not interested, @soksamnanglim can pick it up.

**Comment by soksamnanglim** [comment]
Hi, thanks for opening this issue! 
After a quick comb-through the repo, I don't see boto3 being directly used in `dbt-redshift`. [See here](https://github.com/search?q=repo%3Adbt-labs%2Fdbt-redshift%20boto3&type=code). Is it even being used?

Could we just remove the pin? Or would you prefer updating this? @dataders

**Comment by VersusFacit** [comment]
Backports to be done shortly

**Comment by mikealfare** [comment]
I've verified that `dbt-redshift==1.7.1` on PyPI now installs with `boto3==1.33.10`. This was also applied to `dbt-redshift==1.6.5`. Closing as complete.
