### ISSUE TITLE
[CT-33] Add macro/run-operation for uploading files from local filesystem to S3

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-redshift#64]
### Describe the feature
Prompted by https://github.com/brooklyn-data/dbt_artifacts/issues/60.

Access to a macro such as:
```
{% do adapter.upload_file(file_path, destination) %}
```

would enable dbt_artifacts to become compatible with Redshift. The user would need to create their own S3 bucket, and grant any policies needed.

The adapter already has [boto3](https://github.com/dbt-labs/dbt-redshift/blob/main/setup.py#L74) as a dependency, so no additional packages should be needed.

### Additional context
Please include any other relevant context here.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

**Comment by McKnight-42** [comment]
@NiallRees Thank you for also trying to implement this functionality in Redshift love the idea of having uniformity for how we extend our adapters as much as possible, I will open this up as a good first issue to work on as we did for the `big-query`

**Comment by McKnight-42** [comment]
[boto3 upload_file](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html?highlight=upload_file#S3.Bucket.upload_file) would need to add a new method in `impl.py` to be able to reference within the `adapter.sql` suggested macro.
