### ISSUE TITLE
[ADAP-1022] [Feature] improve handling of disconnect/broken pipe exceptions thrown by redshift-connector

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-redshift#661]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Based on commentary from the redshift-connector team (i.e.  [this](https://github.com/aws/amazon-redshift-python-driver/issues/142) and now that it surfaces better error messages we should update our connection logic to take advantage. 

Specifically we should retry based on the number of configured retries all `InterfaceError`  and `BrokenPipe` exceptions

**Comment by yamjoepobuda** [comment]
We would like this issue to remain open. We are continuing to see intermittent SSH connectivity failures that appear to be client related (provider side). We are not experiencing these failures with other providers who are setup using identical Bastian hosts (Hightouch, Fivetran).
