### ISSUE TITLE
[ADAP-1070] [Bug] `latest` and `1.x.latest` tags for ghcr Docker releases are stale

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-redshift#686]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Look at https://github.com/dbt-labs/dbt-redshift/pkgs/container/dbt-redshift/versions?filters%5Bversion_type%5D=tagged

1.3.0 is tagged as latest:

<img width="262" alt="image" src="https://github.com/dbt-labs/dbt-redshift/assets/44704949/242a1b00-1efc-4dcd-a3ea-5c3abdfe26d2">

### Expected Behavior

1.6.4 is tagged as `latest` and `1.6.latest`:

<img width="271" alt="image" src="https://github.com/dbt-labs/dbt-redshift/assets/44704949/bd5fbcc9-975b-4d87-931e-278d4e450b15">

And the rest of the 1.x minor versions have `1.x.latest` tags as well.

### Steps To Reproduce

See current behavior above.

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-redshift:
```

**Comment by mikealfare** [comment]
@dbeatty10 I noticed this as well a month or so ago. Apparently this isn't something we can fix, nor does it get used. I agree it's a wart, but I'm closing this as "can't do".

**Comment by dbeatty10** [comment]
https://github.com/dbt-labs/dbt-core/pull/9495 fixes the underlying issue (thank you @mikealfare !), and this particular issue will be resolved for each 1.x version of this adapter upon its next patch release.

We are choosing not to address any [un-supported versions](https://docs.getdbt.com/docs/dbt-versions/upgrade-core-in-cloud#latest-releases) at this time, so <=1.4.x will **not** be updated.

Here are the most recent ones for the supported versions of dbt-redshift in [PyPI](https://pypi.org/project/dbt-redshift/#history):
- 1.7.2
- 1.6.5
- 1.5.11

So this will be completely resolved for >=1.5.x when each of the following are released (but only if each is released prior to falling out of support):
- 1.7.3
- 1.6.6
- 1.5.12

**Comment by mikealfare** [comment]
We released 1.5, 1.6, and 1.7 last Thursday and they all showed up with the proper labels under Packages. Closing as complete.
