### ISSUE TITLE
[Bug] Python driver 2.0.918 causes SSL error. Need to revert back to 2.0.917

### ISSUE THREAD

**Issue by amychen1776** [dbt-labs/dbt-redshift#730]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

There is a bug in 2.0.918 which we have updated the dbt-redshift dependencies to (including in dbt Cloud) that causes connecting to RA3 nodes with data sharing to fail with a "Database Error Server refuses SSL" error message.

### Expected Behavior

This should not fail this way. If we revert back to 2.0.917, there should be no impact (per the Redshift team). 

### Steps To Reproduce

1. Pip install redshift driver to point to 2.0.918
2. Connect to a RA3 node with the preview data sharing functionality on
3. run dbt debg

### Environment

```markdown
- OS:
- Python:
- dbt-core: 1.7+
- dbt-redshift: 1.7+
```

**Comment by mikealfare** [comment]
I threw up a [PR](https://github.com/dbt-labs/dbt-redshift/pull/731) to stop the bleeding in the meantime, which simply caps the `redshift-connector` version.

**Comment by mikealfare** [comment]
Re-opening since we neglected to backport this to 1.7.
