### ISSUE TITLE
[Bug] Connection PID Query Causes unnecessary Serverless Billing

### ISSUE THREAD

**Issue by jaswanthikolla** [dbt-labs/dbt-redshift#855]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In Redshift Serverless,  Queries are billed for a minimum of 60 seconds, and they are not billed from connection time. But, This [query](https://github.com/dbt-labs/dbt-redshift/blob/b510298d752711455997c9050d03d8667fb29539/dbt/adapters/redshift/connections.py#L313) is executed right at the connection creation ( Let's say T0) before executing the first query(T1).  This causes the Serverless Redshift to start the queries timer at T0 instead of first query T1, causing the unnecessary billing for  T1 - T0 time period. 

### Expected Behavior

This [query](https://github.com/dbt-labs/dbt-redshift/blob/b510298d752711455997c9050d03d8667fb29539/dbt/adapters/redshift/connections.py#L313)  should be executed right before executing the first query on the connection. If the PID aleady exists, there is no need to do it again.

### Steps To Reproduce

1. Configure DBT profile with Redshift Serverless
2. Open a Connection, and note down the time as T0
3. Execute a  user query, and note down the time as T1
4. Validate that billing starts from by validating it against  table: SYS_SERVERLESS_USAGE

### Environment

```markdown
- OS: NA
- Python: NA
- dbt-core: main 
- dbt-redshift: Main
```

**Comment by amychen1776** [comment]
Closing this one to consolidate issues!
