### ISSUE TITLE
[Bug] Default auto_begin causes unnecessary Serverless Billing

### ISSUE THREAD

**Issue by jaswanthikolla** [dbt-labs/dbt-redshift#856]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Redshift Serverless starts billing from begin till the time either you close the connection or do commit [1]. By default, I am seeing dbt-redshift doing auto_begin as True and it's not configurable. It seems to always begin after queries, which means  we are billed for redshift until DBT closes the connections. 

Also, There is another topic if it make sense to do auto_begin if `autocommit` is True

References: 
1. https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-billing.html  , Following Quote:
> It's important as a best practice to end transactions. If you don't end or roll back an open transaction, Amazon Redshift Serverless continues to use RPU

### Expected Behavior

auto_begin should be configurable and preferably False as default.

### Steps To Reproduce

1. Configure DBT profile with Redshift serverless. 
2. Run a model with query. 
3.  Validate that it's sending additional begin and commit queries, and also query `SYS_SERVERLESS_USAGE` that you are billed even before the query and after the query.

### Environment

```markdown
- OS:NA
- Python: NA
- dbt-core: main 
- dbt-redshift: main
```

**Comment by amychen1776** [comment]
Closing this one to consolidate issues!
