### ISSUE TITLE
[Feature] Support session_token parameter with IAM User Auth

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-redshift#917]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Update IAM User auth: https://github.com/dbt-labs/dbt-redshift/blob/main/dbt/adapters/redshift/connections.py#L218

Acception a sesion_token parameter to allow for the use of temporary IAM credentials

**Comment by amychen1776** [comment]
closing this because we aren't doing it
